## Reminder: Logistic Regression

### Hypothesis
$$ H(X) = \frac{1}{1+e^{-W^T X}} $$

### Cost

$$ cost(W) = -\frac{1}{m} \sum y \log\left(H(x)\right) + (1-y) \left( \log(1-H(x) \right) $$

 - If $y \simeq H(x)$, cost is near 0.
 - If $y \neq H(x)$, cost is high.

### Weight Update via Gradient Descent

$$ W := W - \alpha \frac{\partial}{\partial W} cost(W) $$

 - $\alpha$: Learning rate



---



## 데이터 로드

- pytorch -> 딥러닝프레임웤 혹은 라이브러리
- H(X), Cost 를 이용해서 W 를 구함
- 경사하강 알고리즘 (= Gradient Descent Algorithm)
- Logistic regression -> 범주형 데이터를 다룸
  - 선형회귀분석과 유사하나, 종속 변수가 범주형 데이터 -> 분류 기법으로 볼 수 있음
  - 이진 분류 혹은 여러 클래스의 분류로 나뉨

- 데이터 로드 -> 모델 학습 -> 데이터 평가 -> 결과 예측

In [1]:
# pytorch
import torch
# 최적화 알고리즘 : SGD 
import torch.optim as optim # SGD를 사용하기 위함 (C언어의 include 과정과 유사)

# For reproducibility
torch.manual_seed(1)

# 임의 데이터 생성
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]] # 0: 불합격, 1: 합격

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

# 차이점을 살펴보기 -> numpy의 list 형태와 tensor 형태 
print(x_data)
print(x_train)

print(x_train.shape)
print(y_train.shape)

[[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
torch.Size([6, 2])
torch.Size([6, 1])


## 모델 학습

In [2]:
# 모델 초기화
# 입력데이터 (x) ==> 2
# 출력 (Y) ==> 0 / 1
W = torch.zeros((2, 1), requires_grad=True) # 선언과 동시에 변수 초기화
b = torch.zeros(1, requires_grad=True) # requires_grad=True -> 학습을 위한 변수로 사용

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1) # 여기서, lr=1 -> learning rate: 0.1

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean() # mean() -> 평균값 적용

    # cost로 H(x) 개선
    optimizer.zero_grad() # optimizer의 gradient 다 0으로 초기화
    cost.backward() # cost를 이용해서 옵티마이저 안의 알고리즘 수행
    optimizer.step() # W를 갱신 
    # 이 과정

    # 100번마다 로그 출력
    if epoch % 100 == 0: # 100번 중에 1번만 출력하기 위함
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))


Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


## 데이터 평가

In [3]:
# 이미 W와 b 값을 위에서 구해줬다고 가정
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
#print(hypothesis[:5])

prediction = hypothesis >= torch.FloatTensor([0.5]) # 0.5를 기준으로 매핑
#print(prediction[:5])

#print(prediction[:5])
#print(y_train[:5])

correct_prediction = prediction.float() == y_train
print(correct_prediction[:5]) # 예측값과 정답이 같은지 확인

accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set.'.format(accuracy * 100))

tensor([[True],
        [True],
        [True],
        [True],
        [True]])
The model has an accuracy of 100.00% for the training set.


In [4]:
XX = [[100, 5]]
xx = torch.FloatTensor(XX);

hypothesis = torch.sigmoid(xx.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)


tensor([[True]])
